(define (cont-frac n d k)
    (define (cf n d k c)
        (if (= k c)
            (/ (n k) (d k))
            (/ (n k) (+ (d k) (cf n d (+ k 1) c)))))
    (cf n d 1 k))

(cont-frac (lambda (i) 1.0)
           (lambda (i) 1.0)
           11)